# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: R '3.6.1' sample
    steps:
      - uses: actions/checkout@master
      - name: setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.1' # The R version to download (if necessary) and use.
      - name: Install Dependencies
        run: |
          Rscript -e 'options(Ncpus = 16);install.packages("DT", repos="http://cran.us.r-project.org")'
      - name: Run Things
        run: |
          conda activate r-environment
          which Rscript
          Rscript -e 'print("hello")'

 
