# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-18.04
    name: R '3.6.1' sample
    steps:
      - uses: actions/checkout@master
      - name: Setup R
        uses: actions/setup-R@v1
        with:
          r-version: '3.6.1'
      - run: Rscript -e 'print("hello")'
